blank_issues_enabled: false
contact_links:
  - name: Security issue disclosure
    url: https://angular.io/guide/security#report-issues
    about: Report a security issue in Angular ClassicFramework, CDK, Material, or CLI
  - name: Angular ClassicCLI
    url: https://github.com/ng-angular/angular-cli/issues/new/choose
    about: Issues and feature requests for Angular ClassicCLI
  - name: Angular ClassicMaterial and Components Development Kit (CDK)
    url: https://github.com/angular/components/issues/new/choose
    about: Issues and feature requests for Angular ClassicMaterial
  - name: Support Request
    url: https://github.com/ng-angular/angular/blob/main/CONTRIBUTING.md#question
    about: Questions and requests for support
