---
name: Update Nx Angular
permissions:
  contents: write
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
      - name: Get Nx repo and filter out angular package
        run: |
          mkdir .tmp && cd .tmp
          git clone https://github.com/nrwl/nx.git && cd nx
          # filter only the angular package
          git filter-branch --force --prune-empty --subdirectory-filter packages/angular master
          cd ../..
          git remote add nx .tmp/nx
      - name: Get updates from Nx repo and merge into ours
        run: |
          git fetch nx master
          git checkout -b tmp/angular-updates FETCH_HEAD
          git checkout main && git pull origin main
          git checkout -b chore/update-nx-angular
          # take files from temporary branch and put them where we need them
          git rm -r angular-classic/packages/nx/nx-angular-classic
          git read-tree --prefix angular-classic/packages/nx/nx-angular-classic -u tmp/angular-updates
      - name: Replace '@angular-classic/' with '@angular-classic/' and push
        run: |
          find angular-classic/packages/nx/nx-angular-classic -type f -exec sed -i 's/@angular\//@angular-classic\//g' {} +
          find angular-classic/packages/nx/nx-angular-classic -type f -exec sed -i 's/@nx\/angular/@angular-classic\/nx-angular/g' {} +
          git push origin :chore/update-nx-angular
          git push origin chore/update-nx-angular
      - name: Install JQ
        run: sudo apt-get install jq
        
      - name: Update Angular versions from package.json
        run: |
          VERSION=$(jq -r .version angular-classic/package.json)
          FILES=angular-classic/packages/nx/nx-angular-classic/src/utils/versions.ts
          for FILE in $FILES
          do
              sed -i "s/export const angularVersion = .*;/export const angularVersion = '~$VERSION';/g" $FILE
              sed -i "s/export const angularDevkitVersion = .*;/export const angularDevkitVersion = '~$VERSION';/g" $FILE
              sed -i "s/export const ngPackagrVersion = .*;/export const ngPackagrVersion = '~$VERSION';/g" $FILE
              sed -i "s/export const ngUniversalVersion = .*;/export const ngUniversalVersion = '~$VERSION';/g" $FILE
          done
          git add $FILES
          git commit -m "Update Angular versions"


      - name: Cleanup
        run: |
          git branch -D tmp/angular-updates
          git remote rm nx
          rm -rf .tmp
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Nx Angular
          title: Update Nx Angular
          body: Updates the Nx Angular package to the latest version.
          branch: chore/update-nx-angular
          base: main
          delete-branch: true
