# Update the `events.json` file that powers the [AIO events page](https://angular-classic.com/events) (if
# necessary) and create a pull request.
#
# For more details on the overall process, see
# [aio/scripts/generate-events/README.md](../../aio/scripts/generate-events/README.md).

name: Update AIO events

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # Run every day at 15:00.
    - cron: '0 15 * * *'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  update_events:
    name: Update `events.json` (if necessary)
    if: github.repository == 'ng-classic/ng-classic'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # Setting `persist-credentials: false` prevents the github-action account from being the
          # account that is attempted to be used for authentication, instead the remote is set to
          # an authenticated URL.
          persist-credentials: false
          # This is needed as otherwise the PR creation will fail with `shallow update not allowed` when the forked branch is not in sync.
          fetch-depth: 0
      - name: Generate `events.json`
        run: node aio/scripts/generate-events/index.mjs --ignore-invalid-dates