name: Update AIO Angular Classic CLI help

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.x'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  update_cli_help:
    name: Update Angular Classic CLI help (if necessary)
    if: github.repository == 'ng-classic/ng-classic'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # Setting `persist-credentials: false` prevents the github-action account from being the
          # account that is attempted to be used for authentication, instead the remote is set to
          # an authenticated URL.
          persist-credentials: false
          # This is needed as otherwise the PR creation will fail with `shallow update not allowed` when the forked branch is not in sync.
          fetch-depth: 0
      - name: Generate CLI help
        run: node aio/scripts/update-cli-help/index.mjs
        env:
          ANGULAR_CLI_BUILDS_READONLY_GITHUB_TOKEN: ${{ secrets.ANGULAR_CLI_BUILDS_READONLY_GITHUB_TOKEN }}
